### ISSUE TITLE
Как можно из программы сбросить флаг об авторизации? (granted)

### ISSUE THREAD

**Issue by makkirus** [GyverLibs/Settings#11]
Привет Alex! Супер крутой проект Settings. Огромная благодарность за твои труды.

Вопрос такой: как можно сбросить флаг об авторизации. Чтобы isGranted() стал FALSE.  Иными словами сбросить авторизацию (не заходя в веб интерфейсе в раздел с ключиком). Может можно что-то вызвать или в самой библиотеке что-то самому дописать? Если да.  то что и куда? :) Благодарю.

**Comment by GyverLibs** [comment]
привет, а какую в итоге логику нужно реализовать? Granted поднимается автоматически, если приходит запрос с правильно указанным паролем, это проверяется каждый раз при любом вызове билдера

**Comment by makkirus** [comment]
У меня просто разделение интерфейса на три уровня пользователя: гость, авторизованный пользователь и супер-админ. Я добавил select и переменную, которая выставляет флаг в зависимости от того какой пользователь был выбран. В момент выбора пользователя я вызываю sett.setPass() и делаю подмену пароля для всего портала для конкретного пользователя. Затем вызываю sett.reload(). А пароль пользователь вводит в поле авторизации как это задумано изначально. и в принципе всё получается. Просто ключик горит зеленым если меняешь одного пользователя на другого. Но это мелочь.
