### ISSUE TITLE
Как реализовать дополнительные методы веб-сервера

### ISSUE THREAD

**Issue by ArtemBulavin** [GyverLibs/Settings#13]
Как можно добавить дополнительные методы в http сервер, чтобы получать по ним данные с датчиков?

**Comment by GyverLibs** [comment]
Ну, взять и дописать, руками

**Comment by ArtemBulavin** [comment]
`// простой пример настройки подключения к WiFi
// ESP работает в режиме AP_STA, чтобы всегда был доступ к настройкам через точку доступа
// для упрощения логики работы подключение делается при старте
// Сохранение настроек wifi перезагружает чип

#include <Arduino.h>
#include <GyverDBFile.h>
#include <LittleFS.h>
#include <GyverHTTP.h>
GyverDBFile db(&LittleFS, "/data.db");

#include <SettingsESP.h>
SettingsESP sett("WiFi config", &db);
ghttp::Server<WiFiServer, WiFiClient> server(80);

DB_KEYS(
    kk,
    DB_KEY(wifi_ssid),
    DB_KEY(wifi_pass),
    DB_KEY(apply));

void build(sets::Builder& b) {
    {
        b.Pass(kk::pass, "12345678");
        sets::Group g(b, "WiFi");
        b.Input(kk::wifi_ssid, "SSID");
        b.Pass(kk::wifi_pass, "Пароль");
        if (b.Button(kk::apply, "Сохранить и перезагрузить")) {
            db.update();  // сохраняем БД не дожидаясь таймаута
            ESP.restart();
        }
    }
}

void setup() {
    Serial.begin(115200);
    Serial.println();

    // режим AP_STA. Вызываем перед sett.begin(), чтобы
    // settings знал о текущем режиме wifi
    WiFi.mode(WIFI_AP_STA);

    sett.begin();
    sett.onBuild(build);

    // базу данных запускаем до подключения к точке
#ifdef ESP32
    LittleFS.begin(true);
#else
    LittleFS.begin();
#endif
    db.begin();
    db.init(kk::wifi_ssid, "");
    db.init(kk::wifi_pass, "");

    // ======= AP =======
    WiFi.softAP("AP ESP");
    Serial.print("AP IP: ");
    Serial.println(WiFi.softAPIP());

    // ======= STA =======
    // если логин задан - подключаемся
    if (db[kk::wifi_ssid].length()) {
        WiFi.begin(db[kk::wifi_ssid], db[kk::wifi_pass]);
        Serial.print("Connect STA");
        int tries = 20;
        while (WiFi.status() != WL_CONNECTED) {
            delay(500);
            Serial.print('.');
            if (!--tries) break;
        }
        Serial.println();
        Serial.print("IP: ");
        Serial.println(WiFi.localIP());
    }

    server.begin();

    server.onRequest([](ghttp::ServerBase::Request req) {
        // URL
        Serial.println(req.method());
        Serial.println(req.url());
        Serial.println(req.path());
        Serial.println(req.param("kek"));
        Serial.println(req.param("lol"));

        // BODY
        Serial.println(req.body());
        // req.body().writeTo(Serial);
        // req.body().writeTo(file);
        // req.body().stream.readBytes(buf, req.length());

        // RESPONSE
        if (req.url() == "/answer") {
            // chunked
            server.send("hello");
            server.send(", ");
            server.send("WORLD");

            // single
            // server.sendSingle("HELLO, WORLD");
        } else if (req.url() == "/answer_headers") {
            // добавить свои хэдеры к send
            ghttp::ServerBase::Headers headers(200);
            headers.add("kek-header", "kek value");
            headers.add("another-header", "jello!");
            server.beginResponse(headers);

            server.send("this is ");
            server.send("answer");
        } else if (req.url() == "/file_headers") {
            // добавить свои хэдеры к файлу
            ghttp::ServerBase::Headers headers(200);
            headers.add("file-header", "abcdef");
            server.beginResponse(headers);

            char file[] = "hello!";
            server.sendFile((uint8_t*)file, strlen(file));
        } else {
            server.send(200);
        }
    });
}

void loop() {
    sett.tick();
    server.tick();
}`

методы не срабатывают
наверняка делаю что-то не так, прошу прощения за глупые вопросы, но только разбираюсь с этой темой
буду признателен за помощь в решении вопроса

**Comment by GyverLibs** [comment]
я не понимаю вопрос

**Comment by ArtemBulavin** [comment]
вместо методов веб сервера, которые я описал в коде, срабатывает дефолтная страница настроек

**Comment by GyverLibs** [comment]
так и должно быть

**Comment by ArtemBulavin** [comment]
а как можно добавить свои методы в веб сервер?

**Comment by GyverLibs** [comment]
для чего? Какая конечная логика требуется?

**Comment by ArtemBulavin** [comment]
нужны эндпоитны, к которым сторонний сервис будет обращаться для получения данных с датчиков

**Comment by GyverLibs** [comment]
поднять сервер на другом порту и всё

**Comment by ArtemBulavin** [comment]
спасибо!
еще момент при компиляции вылазит ошибка 
![image](https://github.com/user-attachments/assets/e8ce306e-894e-4752-befc-1b00cff238c3)

**Comment by GyverLibs** [comment]
либо использовать `SettingsESP`, там публичный член `server` и на него можно навесить урлы через `on`

**Comment by ArtemBulavin** [comment]
с сервером разобрался, спасибо!
остался вопрос с ошибкой компиляции

**Comment by GyverLibs** [comment]
аа понятно, доверил и не проверил фиксиков https://github.com/GyverLibs/Settings/pull/12
сейчас исправлю закину обновление

**Comment by ArtemBulavin** [comment]
спасибо большое за помощь и огромный вклад в сообщество)

**Comment by GyverLibs** [comment]
👍👍

**Comment by LittleBuster** [comment]
У меня нет такой ошибки при сборке в VSCode после моего фикса. Если инклудится ota.h, то все хедеры описанные в нем должны автоматом подтягиваться

**Comment by GyverLibs** [comment]
в актуальной версии ядра нужен `#include <flash_hal.h>` для 8266
