### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by whitevast** [GyverLibs/Settings#15]
А можно доработать селект, чтобы в интерфейсе отображался ключ, а в обработчик прилетало значение?
Например, я создаю список "Яблоко:apple;Апельсин:orange;Банан:banana". Соответственно, в интерфейсе отображаются наименования на русском, а в обработчик передаются и в БД сохраняются значения на английском.

**Comment by GyverLibs** [comment]
Но зачем, если в обработчик прилетает индекс, с которым можно реализовать всё что угодно дальше

**Comment by whitevast** [comment]
Чтобы упростить автоматическое сохранение в бд и в файл, а не вылавливать в обработчике значения, а также и для автоматической подгрузки из бд выбранного значения.

**Comment by GyverLibs** [comment]
В смысле упростить, индекс пишется в бд и также подгружается обратно, так и работает select

**Comment by whitevast** [comment]
Так в БД запишется что? Яблоко? И загрузится тоже?

**Comment by GyverLibs** [comment]
В бд пишется индекс

**Comment by whitevast** [comment]
А. Все, туплю ) Дошло.
