### ISSUE TITLE
Слайдер

### ISSUE THREAD

**Issue by whitevast** [GyverLibs/Settings#16]
А можно ли сделать режим слайдера с мгновенной передачей изменного значения. То есть не когда отпустил бегунок, а когда он сдвинулся. Это позволит двигая слайдер видеть, например, изменение яркости подсветки в реальном времени.

**Comment by GyverLibs** [comment]
Да, сделаю, забыл про это

**Comment by brightproject** [comment]
Точно, что-то не то делал, вот так получилось, жму на выключатель и появляется слайдер:
```
if (b.Switch(ag::dim, "Режим DIM", &data.enable_dim, sets::Colors::Yellow)) {
b.reload();
Serial.println(data.enable_dim);
}
if(data.enable_dim) {
    b.Slider(ag::slider, "Минимальный уровень", 20, 80, 10);
    data.slider = db[ag::slider];   
}
```

**Comment by brightproject** [comment]
Спасибо @GyverLibs, а ведь действительно - работает, код регулировки подсветки дисплея слайдером такой:
```
if (b.beginGroup("Подсветка"))
  b.LED("Статус DIM", db[ag::dim], sets::Colors::Black, sets::Colors::Green); // выключенный цвет, включенный цвет
  data.enable_dim = db[ag::dim];
  if (b.Switch(ag::dim, "Режим DIM", &data.enable_dim, sets::Colors::Yellow)) {
    b.reload();
    Serial.println(db[ag::dim]);
  }
  if(db[ag::dim]) {
    b.Slider(ag::slider, "Минимальный уровень", 20, 80, 10); // диапазон 20-80, шаг 10
  }
b.endGroup();
```

В коде крутится задача freeRTOS
```
void pwmTask(void *pvParameters) {
  while (true) {
    // https://docs.espressif.com/projects/arduino-esp32/en/latest/api/ledc.html
    ledcAttachChannel(GPIO_NUM_38, 300, 8, 7); // 0-255
    if(db[ag::dim]) {
      pwm_bl = db[ag::slider]; // ШИМ 8 бит
    }
    if(!db[ag::dim]) {
      pwm_bl = 255; // 8-bit
    }
    ledcWrite(GPIO_NUM_38, pwm_bl);
    vTaskDelay(20 / portTICK_PERIOD_MS); // Update every 50 ms
  }
}
```
Но, полностью уйти от переменных в качестве флага я не могу, такой код не собирается даже

>   // data.enable_dim = db[ag::dim];
>   if (b.Switch(ag::dim, "Режим DIM", &db[ag::dim], sets::Colors::Yellow))

**Comment by GyverLibs** [comment]
Ещё раз - надо определиться, используется бд или переменные. Почитать доку, там всё есть с примерами. Код неправильный в обоих случаях выше

**Comment by brightproject** [comment]
Ранее, я вообще думал, что если флаги для логики `if(){} `брать из `БД`, то наверное будет задержка, ведь измененное значение в `БД` попадает по таймауту, например 5 сек.
Но на деле весь интерфейс вебморды шустро реагирует.
Cнял видео, из браузера на компе, ~~и удалил случайно~~ и первое включение СВИЧА, чтобы раскрыть СЛАЙДЕР происходило с задержкой.
Не знаю, что было, но сейчас все с браузера хром на ПК тоже шустро.

https://github.com/user-attachments/assets/b17e4912-c1fa-43a4-b307-6aa62234eb7c

На айфоне и андроиде такого не замечал. там все сразу реагирует.

> Ещё раз - надо определиться, используется бд или переменные.

Я не могу использовать только БД, потому что мне нужно, чтобы к примеру СВИЧ при загрузке вебморды показал свое актуально состояние, а его только из БД можно взять.
Вот эта часть кода как раз это выполняет

> data.enable_dim = db[ag::dim];
> if (b.Switch(ag::dim, "Режим DIM", &data.enable_dim, sets::Colors::Yellow))

Если я откажусь от переменных и попробую СВИЧу передать значение напрямую, то сборка прошивки не пройдет

> if (b.Switch(ag::dim, "Режим DIM", &db[ag::dim], sets::Colors::Yellow))

Доки читаю, они и правда хорошие, но иногда делаешь нетипичные вещи, а примеров нет🙄

**Comment by brightproject** [comment]
> В доке написано - либо БД, либо переменные.

Хорошо, как мне назначить цвет переключателю, если функция, где можно добавлять цвет, требует переменную в качестве `ptr-ссылки` для своей работы:

> b.Switch("ВКЛЮЧИТЬ", &ag::enable, sets::Colors::Yellow);

А вариант из доков, для работы с переменными, где можно задать 3 параметра, и как раз таки цвет, не принимает ссылку как указатель на `БД`:

> b.Switch("ВКЛЮЧИТЬ", &ag::enable, sets::Colors::Yellow);

Для меня работает первый вариант, второй не собирается даже.

**Comment by GyverLibs** [comment]
> требует переменную в качестве ptr-ссылки

точно так же, как в доке - по умолчанию задаётся `nullptr`

> второй не собирается даже

и не должен, это ошибка

**Comment by brightproject** [comment]
> так нельзя)

Ну в перспективе можно добавить, а то жутко неудобно.
Двигаешь слайдером, увел вправо, отпустил палец все ОК.
Хочешь забрать слайдер справа, жмешь на слайдер, а открывается диалоговое окно - введи число.

https://github.com/user-attachments/assets/e8c5ab56-8ab1-4a36-a440-20275cb01fb6

Как понял, это надо где то в недрах копаться?
```c++
bool _beginWidget(Code type, size_t id, const Text& label, AnyPtr value = nullptr, uint32_t color = SETS_DEFAULT_COLOR)
```

**Comment by GyverLibs** [comment]
нет, такое не надо) в библиотеке всё сделано в едином стиле. Если надо другое - есть поддержка кастомных виджетов на js+css
