### ISSUE TITLE
Сохранение настроек в NVS?

### ISSUE THREAD

**Issue by tarhan** [GyverLibs/Settings#18]
Может я чего-то не понимаю. Но вроде на ESP'шках для настроек, т.е. пар ключ-значение, где значения небольшого объема, у Espressif рекомендуется использовать библиотеку Preferences (на базе NVS).  
Или сейчас так не принято делать?  

Достаточно ли написать свой вариант GyverDBFile ?

**Comment by GyverLibs** [comment]
у esp8266 нет ни NVS, ни Preferences
