### ISSUE TITLE
Не компилируется на последней версии

### ISSUE THREAD

**Issue by phantomdante333** [GyverLibs/Settings#19]
При переходе на последнюю версию,ошибки при компиляции.Откат на предыдущую помогает.

 **no match for call to '(sets::Build) ()'
   83 |     if (b.build().isAction()) {
      |         ~~~~~~~^~
no match for call to '(sets::Build) ()'
   85 |         Serial.print(b.build().id(), HEX);
      |                      ~~~~~~~^~
 no match for call to '(sets::Build) ()'
   87 |         Serial.println(b.build().value());**

**Comment by GyverLibs** [comment]
> v1.1.0
> Методы build(), value(), id() теперь являются членами (build, value, id) для краткости

foo(b.build.id);
