### ISSUE TITLE
Обновление данных в Web

### ISSUE THREAD

**Issue by Oleg-Perevyshin** [GyverLibs/Settings#2]
Всем привет!

Я хочу показывать изменяющиеся данные в Web интерфейсе.
В примере используется GyverDBFile, которая записывает в БД постоянно, если что то изменится в перечисленных ключах.
Хотел узнать, как сделать передачу переменных в Web, но чтоб они не записывались постоянно в БД и не убивали флешку?

Может есть пример какой?

**Comment by GyverLibs** [comment]
Использовать GyverDB вместо GyverDBFile

**Comment by GyverLibs** [comment]
Если нужно отправить именно переменную - то её можно просто передать в виджет как значение
https://github.com/GyverLibs/Settings?tab=readme-ov-file#builder
