### ISSUE TITLE
Не компилируется если выбрать SettingsAsync

### ISSUE THREAD

**Issue by Roman-RV78** [GyverLibs/Settings#21]
Доброго. Ошибка компиляции, пример wificonnect из библиотеки.

Ошибка:

In file included from C:\Temp\.arduinoIDE-unsaved20241021-4516-1rm01py.51fy\wificonnect\wificonnect.ino:14:
d:\arduino\libraries\Settings\src/SettingsAsync.h: In lambda function:
d:\arduino\libraries\Settings\src/SettingsAsync.h:53:74: error: call of overloaded 'beginResponse(fs::LittleFSFS&, String&)' is ambiguous
   53 |                 AsyncWebServerResponse *response = request->beginResponse(ST_FS, path );
      |                                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from d:\arduino\libraries\Settings\src/SettingsAsync.h:12:
d:\arduino\libraries\ESP_Async_WebServer\src/ESPAsyncWebServer.h:366:29: note: candidate: 'AsyncWebServerResponse* AsyncWebServerRequest::beginResponse(FS&, const String&, const char*, bool, AwsTemplateProcessor)'
  366 |     AsyncWebServerResponse* beginResponse(FS& fs, const String& path, const char* contentType = asyncsrv::empty, bool download = false, AwsTemplateProcessor callback = nullptr);
      |                             ^~~~~~~~~~~~~
d:\arduino\libraries\ESP_Async_WebServer\src/ESPAsyncWebServer.h:367:29: note: candidate: 'AsyncWebServerResponse* AsyncWebServerRequest::beginResponse(FS&, const String&, const String&, bool, AwsTemplateProcessor)'
  367 |     AsyncWebServerResponse* beginResponse(FS& fs, const String& path, const String& contentType = emptyString, bool download = false, AwsTemplateProcessor callback = nullptr) { return beginResponse(fs, path, contentType.c_str(), download, callback); }
      |                             ^~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1

Плата DOIT esp32 devkit v1
IDE 2.3.3
SDK 3.1.0 RC3

**Comment by Roman-RV78** [comment]
Можете ссылку на библиотеку? Моя установлена через менеджер библиотек при выводе информации ведёт на эту страницу https://github.com/mathieucarbou/ESPAsyncWebServer и установлен последний релиз.
В менеджере она типа от ME-No-Dev но ведёт на эту страницу, где форк другого автора

**Comment by GyverLibs** [comment]
В ридми рекомендуется конкретный форк async библиотек от esphome

**Comment by Roman-RV78** [comment]
Если про это https://github.com/esphome/ESPAsyncWebServer то arduino ide  не воспринимает её ни в каком виде.

**Comment by GyverLibs** [comment]
Уу, я в ИДЕ не рассматривал работу) посмотрю , может получится поправить универсально

**Comment by GyverLibs** [comment]
а если добавить `emptyString` в SettingsAsync.h 53 строка вот так
```
// было
AsyncWebServerResponse *response = request->beginResponse(ST_FS, path);

// сделать
AsyncWebServerResponse *response = request->beginResponse(ST_FS, path, emptyString);
```

**Comment by Roman-RV78** [comment]
Да спасибо, всё компилируется и работает с этой библиотекой https://github.com/mathieucarbou/ESPAsyncWebServer. Можно закрывать

**Comment by GyverLibs** [comment]
Огонь. Ну не закрывать, а апдейтик выпустить)
