### ISSUE TITLE
'Row' is not a member of 'sets'

### ISSUE THREAD

**Issue by Striagor** [GyverLibs/Settings#22]
void build(sets::Builder& b) {
    b.Input("input1"_h, "Text 1");

    {
        sets::Menu g(b, "Submenu");

        b.Input("input2"_h, "Text 2");
    }
}

беру код из примера и получаю ошибку: 'Row' is not a member of 'sets'

**Comment by GyverLibs** [comment]
ну так надо обновить библиотеку до версии, в которой появился контейнер Row

**Comment by Striagor** [comment]
> ну так надо обновить библиотеку до версии, в которой появился контейнер Row

оуу, и в правду не был обновлен...
