### ISSUE TITLE
Оттенок фона

### ISSUE THREAD

**Issue by mikewap83** [GyverLibs/Settings#23]
Добрый день, а можно поправить чтобы красиво смотрелись кнопки рядом если они в одной строке с другими элементами
![Снимок экрана 2024-12-04 154136](https://github.com/user-attachments/assets/fcbc57fe-dd83-421b-9c4c-aaf3a7b6b75e)
без группы кнопок
![Снимок экрана 2024-12-04 154215](https://github.com/user-attachments/assets/d4f9f30f-8912-4387-ac69-d586c0ce87cf)
если начинать группу кнопок
![Снимок экрана 2024-12-04 154231](https://github.com/user-attachments/assets/153db6c8-5f01-4641-87e3-a0ae538ce19d)

хотелось бы если группа кнопок, чтобы заливка была того же оттенка как и весь фон

**Comment by GyverLibs** [comment]
Привет, спасибо! Сделал
