### ISSUE TITLE
Нижнее подчеркивание в названии сети.

### ISSUE THREAD

**Issue by KudPavel** [GyverLibs/Settings#24]
Не могу ввести сеть TP-Link_8E2A в веб интерфейсе. После попытки подключения название сбрасывается на предыдущее. Вроде как реагирует именно на нижнее подчеркивание _ .

**Comment by GyverLibs** [comment]
Есть контакт?

**Comment by KudPavel** [comment]
Пока не могу проверить (на работе).
Кстати, ввести то оно даёт без проблем, а вот после нажатия Connect заменяется на предыдущее.

**Comment by GyverLibs** [comment]
Ну вот у меня на скрине данные доходят с подчеркиванием в монитор порта

**Comment by KudPavel** [comment]
Дело точно не в подчеркивании. 
Ни в какую не хотело подключаться, пока я не сменил Partition scheme c Huge APP на Minimal SPIFFS, после чего всё стало сохраняться и подключаться. Видимо что то связанное с GyverDB.

**Comment by GyverLibs** [comment]
Gyverdbfile работает с файловой системой и хранит настройки

**Comment by KudPavel** [comment]
Я в курсе. Просто видимо настройки не сохранялись или сохранялись не корректно при Huge APP.

**Comment by GyverLibs** [comment]
100пудов

**Comment by KudPavel** [comment]
Всё равно какая то ерунда с подключением или сохранением. Но с подчеркиванием вроде не связано. Попозже либо разберусь, либо сформулирую в чем проблема, пока не понятно.

**Comment by KudPavel** [comment]
Пример wificonnector просто летает всё работает никаких проблем. Но когда я использую Settings c Fastbot2 и esp_camera, связь становится очень не стабильной. В общем пока закрою этот вопрос, а то еще чего ни будь придумаю.
