### ISSUE TITLE
Дата и время (формат)

### ISSUE THREAD

**Issue by dialmak** [GyverLibs/Settings#25]
Приветствую.
Есть ли возможность как-то принудительно указать формат дати?
У меня вот так выводит, если передаю Unix time, что не соответствует региональным стандартам в Windows.
Формат даты где можно подправить? Предполагаю, что это в js... 

![chrome_zi2F7ltS7F](https://github.com/user-attachments/assets/14451c78-ad09-4b41-837d-f17128a1a3f8)

На смартфоне формат даты тоже не соответствует региональным стандартам, но настройка при клике без AM/PM. Что лучше конечно.
Спасибо.

**Comment by GyverLibs** [comment]
Привет, реализация пикера даты зависит от браузера, всё региональные штуки полностью автоматические, не настраиваются и в разных браузерах работают и сделаны по разному

**Comment by dialmak** [comment]
Ну ОК. Где передача данных конкретнее происходит?

**Comment by GyverLibs** [comment]
Данные передаются просто как unix секунды 32 бит целое
