### ISSUE TITLE
Часовой пояс

### ISSUE THREAD

**Issue by dialmak** [GyverLibs/Settings#26]
Из лога версий:
> Виджеты DateTime и Date теперь выводят и отправляют unix время с учётом часового пояса браузера

Подскажите где ручками отключить этот учет? У меня подключен RTC и хочу видеть реальное время в ESP32.
Спасибо.

**Comment by GyverLibs** [comment]
Нигде. Нужно 
- Либо отправлять время с rtc как unix (utc), тогда в браузере будет реальное локальное время
- Либо отправлять время в виджет Label в виде текста
