### ISSUE TITLE
Вопросы и прикольные ответы

### ISSUE THREAD

**Issue by dialmak** [GyverLibs/Settings#27]
Был вопрос https://github.com/GyverLibs/Settings/issues/26

Ответ
https://github.com/GyverLibs/Settings/issues/26#issuecomment-2535165165
Меня удивил такой ответ Автора
Что конечно не соответствует действительности.

Поработаем ручками. Легко ведь изменить..
Кому тоже нужно, то загружаем  и меняем в https://github.com/GyverLibs/Settings-web.git
`const gmt = new Date().getTimezoneOffset() * 60;`
на 
`const gmt = 0;`
Далее build в комстроке и грузим новый  файл ".\dist\gzip\settings.h" вместо "Settings\src\web\settings.h" и снова конечно upload...

Был второй вопрос
Был вопрос https://github.com/GyverLibs/Settings/issues/25

Меня также удивил такой ответ Автора
https://github.com/GyverLibs/Settings/issues/25#issuecomment-2534853106

Я не спец в js, но думаю легко исправить и эту бяку
Автор использует в 'web-settings-web-main\src\script\widgets\time.js '
функцию 
'new Date((value - gmt) * 1000).toISOString();'
Нужно заменить на 
'new Date((value - gmt) * 1000).toLocaleString();'
Но это не всё, требуется заменить еще зависимости...
Пока в процессе, я не нашел окончательного решения.. Но не в этом суть.

А, что, так можно, писать бред, про браузеры и т.д.? Вопрос риторический...

**Comment by GyverLibs** [comment]
#26 автор приводит два варианта решения проблемы без изменения исходника. Это удивительно? Да, можно обойтись без костылей и форков

#25 реализация пикеров даты, времени, цвета, а также слайдеров и вообще почти всех input'ов зависит от конкретного браузера и не имеет стандартов, как разработчик браузера написал - так оно выводится. Вроде не удивительная вещь, общеизвестная

**Comment by dialmak** [comment]
1. По https://github.com/GyverLibs/Settings/issues/26
Не знаю, вариант есть, и он простой. Вы же мне предлагаете читать у клиента offset и учитывать ..
2. По https://github.com/GyverLibs/Settings/issues/25
Вопрос не в пикерах. Перечитайте вопрос.

**Comment by GyverLibs** [comment]
1. Я вам ничего не предлагаю :) читайте внимательнее, особенно второй вариант. И что такое unix время
2. Я вижу скриншот с пикером и вопрос по нему. Возможно мы видим разное, это вопрос риторический
