### ISSUE TITLE
Опять двойка

### ISSUE THREAD

**Issue by dialmak** [GyverLibs/Settings#28]
По https://github.com/GyverLibs/Settings/issues/26
Не знаю, вариант есть, и он простой. Вы же мне предлагаете читать у клиента offset и учитывать ..
По https://github.com/GyverLibs/Settings/issues/25
Вопрос не в пикерах. Перечитайте вопрос.

**И не нужно закрывать вопрос пока Вам не ответили, это невежливо минимум м смотрится смешно максимум**

**Comment by GyverLibs** [comment]
Эм, не нужно создавать дублирующихся issue, как раз это и есть невежливо. Я закрыл вопрос, потому что он исчерпан, а вы имеете полное право писать в закрытом. И оно не мозолит глаза
