### ISSUE TITLE
Эт хорошо. 

### ISSUE THREAD

**Issue by dialmak** [GyverLibs/Settings#29]
По 25 вопросу, если непонятно
Используется
'new Date((value - gmt) * 1000).toISOString();'
Ну и результат конечно известен, это ISO формат на екране
Для замены на региональные настройки нужен
'new Date((value - gmt) * 1000).toLocaleString();'

Хотя судя по всему Вы не воспринимаете критику вообще.
Эт хорошо. Такие люди нужны Вашей сране.

**Comment by GyverLibs** [comment]
Секунду, а где была критика, я что то пропустил? Дата-время выводится в  универсальном формате ISO. Это факт, а не критика. 

Раз уж мы переходим на личности и страны - обсуждать нам больше нечего, всего доброго.
