### ISSUE TITLE
OTA (предложение)

### ISSUE THREAD

**Issue by Oleg-Perevyshin** [GyverLibs/Settings#3]
Привет!
Либа замечательная и справляется с поставленными задачами!
Подскажите, есть в планах добавление ОТА?
Не хочется использовать Portal или Hub.

**Comment by GyverLibs** [comment]
Привет, да, добавлю ота и файловый менеджер в следующем крупном обновлении

**Comment by Oleg-Perevyshin** [comment]
Хотел еще узнать.
Возможно ли генерировать "налету" содержимое страницы?

В чем суть, мое устройство получает данные от датчиков (количество датчиков может быть разным)
При получении данных я создаю экземпляры структуры и заполняю данными из конкретного датчика.
Соответственно таких экземпляров может быть так же разное количество.

Как можно на Web странице динамически отображать блоки с данными из структур?
Т. е. количество таких блоков будет динамическое, в зависимости от количества датчиков.

Есть у Вас какая то библиотека для ESP с поддержкой подобного функционала?

**Comment by GyverLibs** [comment]
Нет, нативно такого нет и не будет. Максимум можно перезагружать страницу по таймеру

**Comment by Oleg-Perevyshin** [comment]
Благодарю за ответ!
Кстати, я делал проект с веб приложением для ESP, использовал Preact (урезанный и видоизмененный React и очень маленький размер), довольно неплохая тема, можете взять на вооружение.

**Comment by GyverLibs** [comment]
Предпочитаю ванильный js и свои библиотеки

**Comment by GyverLibs** [comment]
сделал ОТА

**Comment by Oleg-Perevyshin** [comment]
О, круто, благодарю!
Кстати, вы рассматривали вариант использования WebSocket для обновления данных на странице?

**Comment by GyverLibs** [comment]
зайти в меню кнопка справа сверху, нажать на облачко, выбрать bin файл
