### ISSUE TITLE
Ошибки компиляции кода, начиная с версии Settings 1.2.0 при добавлении в проект FastBot2

### ISSUE THREAD

**Issue by aleta2020** [GyverLibs/Settings#31]
Доброго времени суток! и с наступающим НГ!!!
Обновил версию Settings 1.1.13 до актуальной (1.2.2 - но пробовал все 1.2.х) - в моем проекте посыпались ноты, предупреждения и ошибки (много). Откатил Settings до 1.1.13 - все нормально. Взял пример demo_data (Settings 1.2.2), просто добавил строчки:
```
#include <FastBot2.h>
FastBot2 bot;
```

Посыпались те же ошибки, что и в моем проекте. 

Связанные с Settings библиотеки обновлены до актуальных версий.
Arduino IDE 1.8.19,
МК wemos D1 mini, 
выбрана плата NodeMCU 1.0 (ESP-12E Module), 
версия ядра esp8266  3.1.2

Вырезал почти все лишнее - вот минимальный код:
```
#include <FastBot2.h>
FastBot2 bot;

#include <GyverDBFile.h>
#include <LittleFS.h>
GyverDBFile db(&LittleFS, "/data2.db");

#include <SettingsGyver.h>
SettingsGyver sett("My Settings", &db);

void setup() {

}

void loop() {
    sett.tick();
}
```
С 1.1.13 компилячится без ошибок и сообщений.
<details>
  <summary>Тут фрагмент лога компиляции 1.2.2:</summary>

```
C:\Users\aaaa_\Documents\Arduino\libraries\GSON\src/utils/bson.h:74:26: note:   initializing argument 1 of 'void BSON::add(const BSON&)'
   74 |     void add(const BSON& bson) {
      |              ~~~~~~~~~~~~^~~~
In file included from C:\Users\aaaa_\Documents\Arduino\libraries\Settings\src/SettingsBase.h:16,
                 from C:\Users\aaaa_\Documents\Arduino\libraries\Settings\src/SettingsGyver.h:8,
                 from G:\TEMPWIN\arduino_modified_sketch_882483\demo_data.ino:11:
C:\Users\aaaa_\Documents\Arduino\libraries\Settings\src/core/builder.h: In member function 'void sets::Builder::Log(size_t, sets::Logger&, su::Text)':
C:\Users\aaaa_\Documents\Arduino\libraries\Settings\src/core/builder.h:113:21: error: no match for call to '(sets::Packet) (char)'
  113 |             (*p)('{');
      |                     ^
C:\Users\aaaa_\Documents\Arduino\libraries\Settings\src/core/builder.h:114:17: error: no match for 'operator[]' (operand types are 'sets::Packet' and 'sets::Code')
  114 |             (*p)[Code::type] = Code::log;
      |                 ^
In file included from C:\Users\aaaa_\Documents\Arduino\libraries\GSON\src/GSON.h:3,
                 from C:\Users\aaaa_\Documents\Arduino\libraries\FastBot2\src/core/core.h:3,
                 from C:\Users\aaaa_\Documents\Arduino\libraries\FastBot2\src/FastBot2Client.h:2,
                 from C:\Users\aaaa_\Documents\Arduino\libraries\FastBot2\src/FastBot2.h:13,
                 from G:\TEMPWIN\arduino_modified_sketch_882483\demo_data.ino:4:
C:\Users\aaaa_\Documents\Arduino\libraries\GSON\src/utils/bson.h:90:11: note: candidate: 'BSON& BSON::operator[](uint16_t)'
   90 |     BSON& operator[](uint16_t key) {
      |           ^~~~~~~~
C:\Users\aaaa_\Documents\Arduino\libraries\GSON\src/utils/bson.h:90:31: note:   no known conversion for argument 1 from 'sets::Code' to 'uint16_t' {aka 'short unsigned int'}
   90 |     BSON& operator[](uint16_t key) {
      |                      ~~~~~~~~~^~~
C:\Users\aaaa_\Documents\Arduino\libraries\GSON\src/utils/bson.h:94:11: note: candidate: 'BSON& BSON::operator[](su::Text)'
   94 |     BSON& operator[](Text key) {
      |           ^~~~~~~~
C:\Users\aaaa_\Documents\Arduino\libraries\GSON\src/utils/bson.h:94:27: note:   no known conversion for argument 1 from 'sets::Code' to 'su::Text'
   94 |     BSON& operator[](Text key) {
      |                      ~~~~~^~~

```

</details>

**Comment by GyverLibs** [comment]
Нужно обновить все библиотеки-зависимости

**Comment by aleta2020** [comment]
проверил по версиям в IDE - стоят самые актуальные, что выдает менеджер библиотек

- GTL v1.1.14
- GyverDB v1.1.8
- StringUtils v1.4.28
- GyverHTTP v1.0.23
- BSON v2.0.3

**Comment by GyverLibs** [comment]
GSON стоит старая

**Comment by aleta2020** [comment]
![image](https://github.com/user-attachments/assets/510e1e53-cb29-4ba2-81b3-64a4dd0f27c3)
У меня стоит 1.5.11, какая должна быть?

**Comment by aleta2020** [comment]
Странно, что IDE не показывает - на сайте 1.6 уже!!! Щас попробую...

**Comment by GyverLibs** [comment]
1.6.0 да

**Comment by aleta2020** [comment]
С библиотекой какие-то чудеса: в IDE показывает только до 1.5.11. 
Я папку GSON удалил. Скопировал с github 1.6.0 архив и установил его из IDE (добавить ZIP библиотеку). IDE ругнулся следующим сообщением:
![image](https://github.com/user-attachments/assets/2fb9e254-3422-4029-aed2-09248a713ec9)
типа: недопустимые символы в имени скетча. Я заменил пробелы на символ подчеркивания - все стало работать без сообщений. Проект компилируется без ошибок. Спасибо!
Но остался вопрос: почему библиотека сама не обновилась и не показывается в менеджере библиотек? Может из-за пробелов? Или у меня на компе что-то слетело?

**Comment by aleta2020** [comment]
Да, и в 2.3.4 тоже самое - не видит обновлений.
1.5.12 и 1.6.0 от 1.5.11 отличаются наличием примера "test NULL type" (папка и файл). Может IDE это не нравится, когда она лезет на github?  Если попробовать переименовать?  :-)

**Comment by GyverLibs** [comment]
Блин..... Скорее всего. Это мне PR закинули, Я мельком глянул - вроде ок. Надо пропиздон устроить будет

**Comment by GyverLibs** [comment]
спасбио

**Comment by aleta2020** [comment]
Может нужно подождать обновлений на серверах, но пока чуда не случилось  :-(  Сообщение о пробелах исчезло, но в списке версий 1.6.1 не появилась. Если удалить папку и установить 1.6.1 из ZIP, то в менеджере 1.8.19 картина такая (как будто GSON не установлен):
![image](https://github.com/user-attachments/assets/01395b7f-f8c9-4548-b87b-5922bcdf17e2)
А в 2.3.4 показывает в списке версий только до 1.5.10. Типа версию 1.5.11 не видит...

**Comment by GyverLibs** [comment]
Реестр обновляется в течение суток

**Comment by aleta2020** [comment]
> Реестр обновляется в течение суток

Все обновилось и заработало: IDE видит все версии (кроме "битых")!!! **Спасибо с новым годом!**

**Comment by GyverLibs** [comment]
Урааа спасибо за репорт
