### ISSUE TITLE
Google Maps (предложение)

### ISSUE THREAD

**Issue by Oleg-Perevyshin** [GyverLibs/Settings#4]
Приветствую!
Хорошая и легкая либа!

Подскажите, есть возможность добавить компонент типа Google Maps или подобной?
Хотелось бы периодически отправлять данные GPS и видеть точку на карте.

Или возможно есть нечто подобное в других либах для Web интерфейса?

**Comment by GyverLibs** [comment]
Привет, карты есть в gyverhub dev ветке
