### ISSUE TITLE
Флажки и Группы переключателей

### ISSUE THREAD

**Issue by mikewap83** [GyverLibs/Settings#5]
Можно добавить Флажки и Группы переключателей

![Снимок экрана 2024-08-13 105300](https://github.com/user-attachments/assets/7eb249cf-d5ef-4e73-8e05-f45e4c2be9c7)
![Снимок экрана 2024-08-13 105345](https://github.com/user-attachments/assets/257a45ed-03f1-4748-88cf-e8525ddf56ee)

**Comment by GyverLibs** [comment]
Виджет Select полностью заменяет переключатели. Флажки это хорошо, но неудобно парсить результат в скетче. Также флажки замечательно заменяются группой свитчей Switch
