### ISSUE TITLE
Перфекционизм

### ISSUE THREAD

**Issue by mikewap83** [GyverLibs/Settings#6]
А можно новый значек состояния подключения перенести вправо перед кнопкой настройки, и выровнять по высоте, а то как то весь вид портится

**Comment by GyverLibs** [comment]
нужно выносить вопрос на голосование, на мой взгляд значок на своём месте и в других местах это как и будет испорченный вид

**Comment by mikewap83** [comment]
Вот так было
![Было](https://github.com/user-attachments/assets/9f846c69-abcc-4aae-abb3-b28cae0a68a2)
Вот так стало
![стало](https://github.com/user-attachments/assets/f0e31766-2039-469b-a7ab-3d536c6b809c)
Вот так хочется
![нужно](https://github.com/user-attachments/assets/9dfa7c67-152c-413b-b8ba-120c61a4322f)

**Comment by GyverLibs** [comment]
я и из текстового описания понял как хочется

**Comment by GyverLibs** [comment]
можно заменить его на "проценты", будет выглядеть лаконично

**Comment by mikewap83** [comment]
Да пускай значек будет, очень симпатично выглядит

**Comment by GyverLibs** [comment]
типо так
![image](https://github.com/user-attachments/assets/39a52743-45b4-4e2d-95b7-57e01b7f5b0b)

**Comment by mikewap83** [comment]
Не плохо смотрится, нужно делать на выбор :)  и вкаком месте ставить

**Comment by GyverLibs** [comment]
на выбор это уже перебор)

**Comment by mikewap83** [comment]
Согласен, пускай будет повернут на 45 градусов
