### ISSUE TITLE
Ввод времени на iPhone

### ISSUE THREAD

**Issue by whitevast** [GyverLibs/Settings#8]
На iPhone не появляется окошко для ввода времени, и, возможно, даты.

**Comment by GyverLibs** [comment]
В стандартном браузере? А если попробовать хром/Яндекс?

**Comment by whitevast** [comment]
Где-то видел информацию, что они все используют один движок. И да, в Яндекс браузере то же самое - никакой реакции на тап по времени.

**Comment by GyverLibs** [comment]
Один движок у хрома/Яндекса, у сафари другой. На других устройствах в Яндексе работает?

**Comment by whitevast** [comment]
Нет, движок у всех один.
https://appleinsider.ru/ios/na-iphone-vyjdut-polnocennye-chrome-i-mozilla-na-svoix-dvizhkax-chto-eto-i-zachem-oni-nuzhny.html
На планшете с Андроидом работает.

**Comment by GyverLibs** [comment]
сделал пачку вариантов, нужно протестировать на айосах https://gyver.ru/

**Comment by whitevast** [comment]
Работают первый, 5 вторая кнопка и 7. 1 и 5 появляется календарь посередине, 7 прикольно разворачивается рядом с кнопкой

**Comment by whitevast** [comment]
https://github.com/user-attachments/assets/117b615c-a81e-43c9-aa18-a8f21d1285ca

**Comment by GyverLibs** [comment]
блин ну и чушь этот ваш ios!

**Comment by GyverLibs** [comment]
- какая версия сафари/iOS?
- выбор цвета работает? Виджет Color
- открыть https://gyver.ru/ , в самом верху надпись showPicker. Рядом OK или ERROR?

**Comment by whitevast** [comment]
iOS 16.7.1. Сафари отдельной версии не имеет.
Выбор цвета НЕ работает.
Рядом с надписью ОК.

**Comment by GyverLibs** [comment]
ну и хуит@ кривая)

**Comment by whitevast** [comment]
Не ругайся ) Купи Айфон и будет счастье )

**Comment by GyverLibs** [comment]
Зачем, на Айфоне я не смогу пользоваться библиотекой 😉

**Comment by whitevast** [comment]
Нее, это не так работает: тебе придется доработать библиотеку, чтоб ей пользоваться )))

**Comment by GyverLibs** [comment]
Может мне ещё движок браузера им доработать, чтобы стандартные фичи работали?)

**Comment by whitevast** [comment]
Вооооо! Они были бы рады!

**Comment by GyverLibs** [comment]
обновил https://gyver.ru/

**Comment by whitevast** [comment]
То же самое, что и в первый раз, за исключением. что в настольном Яндекс теперь не работает тоже ) В том числе, и номер 7, который работает на iPhone/

**Comment by GyverLibs** [comment]
ожидаемо

**Comment by GyverLibs** [comment]
ну, будем ждать что какой нибудь неравнодушный веб разработчик пофиксит под кривой сафари

**Comment by GyverLibs** [comment]
ещё вариант на gyver.ru - проверь, работают ли именно кнопки. Пример прямо из документации, в которой заявлена поддержка на safari

**Comment by GyverLibs** [comment]
а, стоп, отмена. Баг известен уже несколько лет и все на него забили https://bugs.webkit.org/show_bug.cgi?id=234009
В общем на ванильном ios-вебкит это не будет работать, пока его не починят

**Comment by whitevast** [comment]
Нет ( Работают кружки с цветом  и кнопки выбора файлов.

**Comment by whitevast** [comment]
> а, стоп, отмена. Баг известен уже несколько лет и все на него забили https://bugs.webkit.org/show_bug.cgi?id=234009 В общем на ванильном ios-вебкит это не будет работать, пока его не починят

Весело... Похоже это никто не использует, кроме тебя ))) Ни разу с подобным не сталкивался, не считая особого требования к дате, как в IE.

**Comment by GyverLibs** [comment]
ну, на совсем простеньких сайтах используют родной ванильный инпут, который сложно стилизовать и вообще как то настроить. В серьёзных проектах используют полностью кастомное окошко ввода. А я где то посередине и вызываю стандартное окошко со своей кнопки

**Comment by whitevast** [comment]
) Я верю в тебя!

**Comment by GyverLibs** [comment]
а я чё, это люди верят в крутость айфонов)

**Comment by whitevast** [comment]
Ну не крутость. Никакой айфон по ней с тобой не сравнится ))) Для меня он просто удобен, несмотря на все его ограничения. Но это не место для обсуждения неудобств айфонов. Здесь мы обсуждаем только неудобство пользования твоей библиотекой на айфоне 😉

**Comment by GyverLibs** [comment]
> Нет, движок у всех один.
> https://appleinsider.ru/ios/na-iphone-vyjdut-polnocennye-chrome-i-mozilla-na-svoix-dvizhkax-chto-eto-i-zachem-oni-nuzhny.html

Ну вот как эпл расчехлится и разрешит использовать сторонние движки - заработает в айосном хроме/яндексе/мозилле итд

**Comment by whitevast** [comment]
Ну так то тока в Европе. К нам вряд-ли дойдет...

**Comment by whitevast** [comment]
Не в тему, но все же... В ридми нет описания Timer. Даже упоминания нет.

**Comment by GyverLibs** [comment]
не определился, нужен он вообще или нет. С появлением [Looper](https://github.com/GyverLibs/Looper) подобные таймеры утратили смысл

**Comment by GyverLibs** [comment]
В общем я сделаю костыль именно для айфонов, завтра покидаю на тест разные конструкции

**Comment by GyverLibs** [comment]
https://gyver.ru/ надо скриншотов навалить

**Comment by whitevast** [comment]
https://github.com/user-attachments/assets/f6264427-dd0d-4fda-82c0-91a7e51e41c7

**Comment by GyverLibs** [comment]
Неплохо, всё получится

**Comment by AlexGyver** [comment]
сделал на тест, заменить файл в библиотеке src/web

[settings.zip](https://github.com/user-attachments/files/16917202/settings.zip)

**Comment by whitevast** [comment]
Все супер. Все работает: время и дата и время с датой, и выбор цвета. Я же говорил, ты справишься! ;)

**Comment by GyverLibs** [comment]
Я не говорил что не справлюсь, просто это очень некрасивые костыли ради одного единственного забагованного браузера)

**Comment by GyverLibs** [comment]
спасибо за тесты, залил апдейт ❤️

**Comment by whitevast** [comment]
Еще есть предложение, касающееся этих самих полей ввода. Можно сделать обратное: чтобы дата/время отображались, но не редактировались. То есть сделать их виджетами. Например, нужно для отображения рассчитанных рассвета/заката.

**Comment by GyverLibs** [comment]
Для всего, что нужно отобразить но не редактировать, есть виджет label

**Comment by whitevast** [comment]
Неее. У меня есть unixtime. Если я его отправлю на страничку, то на страничке я увижу unixtime. Но я человек и хочу видеть ДД.ММ.ГГ ЧЧ:ММ:CC. То есть нужно, чтоб страничка пересчитывала время в человеческий формат, а не нагружать этим МК.

**Comment by GyverLibs** [comment]
Берешь и отправляешь его строкой. Про нагрузку на МК это смех, особенно в контексте того что прямо в этом момент идёт синхронная обработка http запроса и ответ клиенту, что по времени выполнения несравнимо на много порядков

**Comment by whitevast** [comment]
Ладно ) Мое дело предложить ) Тем более, что DateTime уже пересчитывает это все.

**Comment by GyverLibs** [comment]
можно сделать параметр disable для всех виджетов, но это сильно удлинит функцию и будет похоже на gyverhub первых версий

**Comment by whitevast** [comment]
Не, усложнений точно не надо. Буду преобразовывать на МК. Не заморачивайся.
